// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 *
 * * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 使用自动生成的侧边栏
  // 这样你只需要在 docs 文件夹中创建文件和文件夹，它们就会自动显示
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // 从 docs 根目录开始自动生成
    },
  ],
};

export default sidebars;
